---
title: "p8105_hw3_sk4970"
output: github_document
---

```{r, include = FALSE,message=FALSE,warning=FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)

library(p8105.datasets) 

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 1
```{r}
# importing data
data("instacart")

instacart = 
  instacart %>% 
  as_tibble(instacart)

# each row respresent a single product from an instacart order. Variables include identifiers for user, order, and product; the order in which each product was added to the cart. There are several order-level variables, describing the day and time of the order, and number of days since prior order. Then there are several item-specific variables, describing the product name (e.g. Yogurt, Avocado), department (e.g. dairy and eggs, produce), and aisle (e.g. yogurt, fresh fruits), and whether the item has been ordered by this user in the past. 
```
In total, there are `r instacart %>% select(product_id) %>% distinct %>% count` products found in `r instacart %>% select(user_id, order_id) %>% distinct %>% count` orders from `r instacart %>% select(user_id) %>% distinct %>% count` distinct users.


```{r}
# Below is a table summarizing the number of items ordered from aisle. In total, there are 134 aisles, with fresh vegetables and fresh fruits holding the most items ordered by far.

instacart %>% 
  count(aisle) %>% 
  arrange(desc(n))
```


```{r}
# The plot below shows the number of items ordered in each aisle. Here, aisles are ordered by ascending number of items.

instacart %>% 
  count(aisle) %>% 
  filter(n > 10000) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  ggplot(aes(x = aisle, y = n)) + 
  geom_point() + 
  labs(title = "Number of items ordered in each aisle") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))

```


```{r}
# Next table shows the three most popular items in aisles `baking ingredients`, `dog food care`, and `packaged vegetables fruits`, and includes the number of times each item is ordered in your table.

instacart %>% 
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>%
  group_by(aisle) %>% 
  count(product_name) %>% 
  mutate(rank = min_rank(desc(n))) %>% 
  filter(rank < 4) %>% 
  arrange(desc(n)) %>%
  knitr::kable()
```

```{r}
# The below table shows the mean hour of the day at which Pink Lady Apples and Coffee Ice Cream are ordered on each day of the week. This table has been formatted in an untidy manner for human readers. Pink Lady Apples are generally purchased slightly earlier in the day than Coffee Ice Cream, with the exception of day 5.

instacart %>%
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>%
  summarize(mean_hour = mean(order_hour_of_day)) %>%
  spread(key = order_dow, value = mean_hour) %>%
  knitr::kable(digits = 2)
```

# Problem 2
```{r}
# importing data
accel = read_csv(file = "./accel_data.csv") %>%
  janitor::clean_names()

# pivoting data to tidy
  acceler = 
  pivot_longer(
    accel, 
    activity_1:activity_1440, 
    names_to = "activity_num",
    names_repair = "minimal", 
    values_to = "activity") 
    
  accelerometer = subset(acceler, select = -activity_num)
  
# create weekday vs. weekend variable
 accelerometer %>%
   mutate(day_type = case_when(day == 'Saturday' ~ 'weekend', day == 'Sunday' ~ 'weekend', TRUE ~ 'weekday'))
 
 ## the data set has 5 variables--week, day id, day, activity, and day type with 50,400 observations.

# total activity variable 
 accelerometer %>%
   group_by(day_id) %>%
   mutate(sum_by_group = sum(activity)) %>%
   table
 
 ## sums are the same for each day
  
# plot of 24-hour activity 
 ggplot(accelerometer, aes(x = day_id, y = activity)) +
      geom_line(aes(color = day), alpha = .3)
        
 ## there seems to be increased activity at the beginning and end of the week.
```

# Problem 3
```{r}
# importing data
data("ny_noaa")

# cleaning up data including separating date variable, making preciption in mm and temps to degrees C)
noaa = 
  ny_noaa %>% 
  as_tibble(ny_noaa) %>%
  janitor::clean_names() %>%
  na.omit("") %>%
  separate(col = date, into = c('year','month', 'day'), sep = '-')  %>%
  mutate(perc = prcp * 10) %>%
  mutate(tmax = as.numeric(tmax)) %>%
  mutate(tmin = as.numeric(tmin)) %>%
  mutate(max_temp = tmax * 10) %>%
  mutate(min_temp = tmin * 10) 
  
## there are many missing values for some measurements so I removed them. There are 12 variables and over 1 million observations. Preciption, snowfall, and snow depth are all in mm. Temps are in degrees C. 


sort(table('snow'), decreasing = TRUE)
## 1 mm of snowfall is the most commonly observed value

# two-panel plot Jan. & July max temp by year
  noaa %>%
  group_by(month, year, id) %>% 
  filter(
    month == "January",
    month == "July") %>% 
  summarize(
    tmax_mean = mean(max_temp, na.rm = TRUE), .groups = 'drop'
  ) %>% 
  ggplot(aes(x = year, y = tmax_mean, group = id)) +
  geom_line(alpha = 0.5) +
  facet_grid(. ~ 'month')

  
## There is a higher max temp in July. There are some outliers in January.
  
# two-panel plot with tmax vs. tmix and plot showing 0 > snowfall < 100 by year
  noaa %>%
    group_by(year) %>%
    filter(snow > 0 & snow < 100) %>%
  ggplot(aes(x = min_temp, y = max_temp)) +
    geom_point(aes(color = snow), alpha = 0.3)
    facet_grid(. ~ year)
  
  

```